export const FILL_POSTS = 'FILL_POSTS';
export const FETCH_POSTS_ASYNC = 'FETCH_POSTS_ASYNC';
export const CREATE_POST_ASYNC = 'CREATE_POST_ASYNC';
export const ADD_CREATED_POST = 'ADD_CREATED_POST';
